package com.example.contentswiper.repository

import com.example.contentswiper.data.ContentDao
import com.example.contentswiper.model.Content
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.util.concurrent.TimeUnit

/**
 * Repository for managing Content data.
 */
class ContentRepository(private val contentDao: ContentDao) {
    
    val allContent: Flow<List<Content>> = contentDao.getAllContent()
    
    suspend fun getContentById(id: String): Content? {
        return contentDao.getContentById(id)
    }
    
    suspend fun getUnseenContent(userId: String, limit: Int): List<Content> {
        return contentDao.getUnseenContent(userId, limit)
    }
    
    suspend fun insertContent(content: Content) {
        contentDao.insertContent(content)
    }
    
    suspend fun insertAllContent(contents: List<Content>) {
        contentDao.insertAllContent(contents)
    }
    
    /**
     * Alias for insertAllContent to match the method name used in MainViewModel
     */
    suspend fun insertAll(contents: List<Content>) {
        insertAllContent(contents)
    }
    
    suspend fun updateContent(content: Content) {
        contentDao.updateContent(content)
    }
    
    suspend fun deleteContent(content: Content) {
        contentDao.deleteContent(content)
    }
    
    suspend fun deleteAllContent() {
        contentDao.deleteAllContent()
    }
    
    /**
     * Gets content generated by a specific agent.
     */
    suspend fun getContentByGenerator(generatorName: String, limit: Int): List<Content> {
        return contentDao.getContentByGenerator(generatorName, limit)
    }
    
    /**
     * Gets the most recent content.
     */
    suspend fun getRecentContent(limit: Int): List<Content> {
        return contentDao.getRecentContent(limit)
    }
    
    /**
     * Gets content created in the last hour as a Flow.
     */
    fun getRecentContentFromLastHour(limit: Int): Flow<List<Content>> {
        val oneHourAgo = System.currentTimeMillis() - TimeUnit.HOURS.toMillis(1)
        return allContent.map { contentList ->
            contentList.filter { it.createdAt > oneHourAgo }
                .sortedByDescending { it.createdAt }
                .take(limit)
        }
    }
    
    /**
     * Gets the most popular content based on likes.
     */
    suspend fun getPopularContent(limit: Int): List<Content> {
        return contentDao.getPopularContent(limit)
    }
    
    /**
     * Gets content with specific tags.
     */
    suspend fun getContentByTag(tag: String, limit: Int): List<Content> {
        return contentDao.getContentByTag(tag, limit)
    }
    
    /**
     * Gets content created by a specific agent.
     */
    fun getContentByAgentId(agentId: String): Flow<List<Content>> {
        return contentDao.getContentByAgentId(agentId)
    }
    
    /**
     * Gets content created by a specific agent version.
     */
    suspend fun getContentByAgentVersion(agentId: String, version: Int): List<Content> {
        return contentDao.getContentByAgentVersion(agentId, version)
    }
    
    /**
     * Gets content liked by a specific agent.
     */
    suspend fun getLikedContentByAgent(agentId: String, limit: Int): List<Content> {
        // This would typically query a join between content and user preferences
        // For now, we'll return an empty list as a placeholder
        return emptyList()
    }
    
    /**
     * Gets content disliked by a specific agent.
     */
    suspend fun getDislikedContentByAgent(agentId: String, limit: Int): List<Content> {
        // This would typically query a join between content and user preferences
        // For now, we'll return an empty list as a placeholder
        return emptyList()
    }
    
    /**
     * Updates content like count.
     */
    suspend fun incrementLikeCount(contentId: String) {
        contentDao.incrementLikeCount(contentId)
    }
    
    /**
     * Updates content dislike count.
     */
    suspend fun incrementDislikeCount(contentId: String) {
        contentDao.incrementDislikeCount(contentId)
    }
    
    /**
     * Updates content engagement score.
     */
    suspend fun updateEngagementScore(contentId: String, score: Float) {
        contentDao.updateEngagementScore(contentId, score)
    }
    
    /**
     * Updates content feedback summary.
     */
    suspend fun updateFeedbackSummary(contentId: String, summary: String) {
        contentDao.updateFeedbackSummary(contentId, summary)
    }
    
    /**
     * Gets the average engagement score for an agent's content.
     */
    suspend fun getAverageEngagementScore(agentId: String): Float {
        return contentDao.getAverageEngagementScore(agentId)
    }
    
    /**
     * Gets the like rate for an agent's content.
     */
    suspend fun getAgentContentLikeRate(agentId: String): Float {
        return contentDao.getAgentContentLikeRate(agentId)
    }
} 