package com.example.contentswiper.data

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.example.contentswiper.model.Content
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for the Content entity.
 */
@Dao
interface ContentDao {
    @Query("SELECT * FROM content ORDER BY createdAt DESC")
    fun getAllContent(): Flow<List<Content>>
    
    @Query("SELECT * FROM content WHERE id = :id")
    suspend fun getContentById(id: String): Content?
    
    @Query("SELECT * FROM content WHERE id NOT IN (SELECT contentId FROM user_preferences WHERE userId = :userId) ORDER BY createdAt DESC LIMIT :limit")
    suspend fun getUnseenContent(userId: String, limit: Int): List<Content>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertContent(content: Content): Long
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAllContent(contents: List<Content>)
    
    @Update
    suspend fun updateContent(content: Content)
    
    @Delete
    suspend fun deleteContent(content: Content)
    
    @Query("DELETE FROM content")
    suspend fun deleteAllContent()
    
    /**
     * Gets content generated by a specific agent.
     */
    @Query("SELECT * FROM content WHERE generatedBy = :generatorName ORDER BY createdAt DESC LIMIT :limit")
    suspend fun getContentByGenerator(generatorName: String, limit: Int): List<Content>
    
    /**
     * Gets the most recent content.
     */
    @Query("SELECT * FROM content ORDER BY createdAt DESC LIMIT :limit")
    suspend fun getRecentContent(limit: Int): List<Content>
    
    /**
     * Gets the most popular content based on likes.
     */
    @Query("SELECT c.* FROM content c JOIN user_preferences p ON c.id = p.contentId WHERE p.isLiked = 1 GROUP BY c.id ORDER BY COUNT(p.id) DESC LIMIT :limit")
    suspend fun getPopularContent(limit: Int): List<Content>
    
    /**
     * Gets content with specific tags.
     */
    @Query("SELECT * FROM content WHERE tags LIKE '%' || :tag || '%' ORDER BY createdAt DESC LIMIT :limit")
    suspend fun getContentByTag(tag: String, limit: Int): List<Content>
    
    /**
     * Gets content created by a specific agent.
     */
    @Query("SELECT * FROM content WHERE agentId = :agentId ORDER BY createdAt DESC")
    fun getContentByAgentId(agentId: String): Flow<List<Content>>
    
    /**
     * Gets content created by a specific agent version.
     */
    @Query("SELECT * FROM content WHERE agentId = :agentId AND agentVersion = :version ORDER BY createdAt DESC")
    suspend fun getContentByAgentVersion(agentId: String, version: Int): List<Content>
    
    /**
     * Updates content like count.
     */
    @Query("UPDATE content SET likeCount = likeCount + 1 WHERE id = :contentId")
    suspend fun incrementLikeCount(contentId: String)
    
    /**
     * Updates content dislike count.
     */
    @Query("UPDATE content SET dislikeCount = dislikeCount + 1 WHERE id = :contentId")
    suspend fun incrementDislikeCount(contentId: String)
    
    /**
     * Updates content engagement score.
     */
    @Query("UPDATE content SET engagementScore = :score WHERE id = :contentId")
    suspend fun updateEngagementScore(contentId: String, score: Float)
    
    /**
     * Updates content feedback summary.
     */
    @Query("UPDATE content SET feedbackSummary = :summary WHERE id = :contentId")
    suspend fun updateFeedbackSummary(contentId: String, summary: String)
    
    /**
     * Gets the average engagement score for an agent's content.
     */
    @Query("SELECT AVG(engagementScore) FROM content WHERE agentId = :agentId")
    suspend fun getAverageEngagementScore(agentId: String): Float
    
    /**
     * Gets the like rate for an agent's content.
     */
    @Query("SELECT CASE WHEN (likeCount + dislikeCount) > 0 THEN CAST(likeCount AS FLOAT) / (likeCount + dislikeCount) ELSE 0 END FROM content WHERE agentId = :agentId")
    suspend fun getAgentContentLikeRate(agentId: String): Float
} 