package com.example.contentswiper.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

/**
 * Represents a piece of content generated by GPT-4o that can be swiped in the app.
 */
@Entity(tableName = "content")
data class Content(
    @PrimaryKey
    val id: String = UUID.randomUUID().toString(),
    val title: String,
    val description: String,
    val imageUrl: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val generatedBy: String = "GPT-4o",
    val metadata: Map<String, String> = emptyMap()
) 